name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: pip

      - name: Install build tools
        run: python -m pip install build twine

      - name: Build distribution
        run: python -m build

      - name: Check distribution
        run: python -m twine check dist/*

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish distribution to PyPI
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: pypi
      url: https://pypi.org/p/daikin-onecta
    permissions:
      id-token: write

    steps:
      - name: Download distribution
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
